apiVersion: v1
kind: Service
metadata:
  name: appointment-api
  labels: 
    app: appointment-api
spec:
  type: ClusterIP
  selector:             # indicates into which pods ClusterIP provides access
    app: appointment-api
  ports:
    - port: 8081          # port exposed outside ClusterIP
      targetPort: 8081    # port exposed by Pod
